#!/usr/bin/env bash
# Simple helper to create a local config.js from environment variables or interactive input.
# Usage:
#   (1) Set env vars and run:
#       NASA_API_KEY=A8tgVmkQzQwHej4dPOLKkh1sGw2GAFJtrGpQ4b8A OMDB_API_KEY=b079e78c ./scripts/generate-config.sh
#   (2) Or run without env vars and you'll be prompted.

set -euo pipefail

CONFIG_FILE="config.js"

# Read from env or prompt
NASA_KEY=${A8tgVmkQzQwHej4dPOLKkh1sGw2GAFJtrGpQ4b8A-}
OMDB_KEY=${b079e78c-}

if [ -z "$NASA_KEY" ]; then
  read -r -p "Enter NASA API key (or leave blank to use DEMO_KEY): " NASA_KEY
fi

if [ -z "$OMDB_KEY" ]; then
  read -r -p "Enter OMDb API key (optional): " OMDB_KEY
fi

# Default to DEMO_KEY if empty
if [ -z "$NASA_KEY" ]; then
  NASA_KEY="DEMO_KEY"
fi

cat > "$CONFIG_FILE" <<EOF
// Local runtime config for NASA Space Explorer
// Generated by scripts/generate-config.sh
window.NASA_CONFIG = {
  APOD_API_KEY: '${A8tgVmkQzQwHej4dPOLKkh1sGw2GAFJtrGpQ4b8A}',
  OMDB_API_KEY: '${OMDB_KEY}'
};
EOF

printf "Wrote %s\n" "$CONFIG_FILE"
printf "Note: %s is in .gitignore so it won't be committed. Keep your keys safe.\n" "$CONFIG_FILE"

exit 0
